import * as React from "react";
import * as System from "office-ui-fabric-react";
import { ControlType, PropertyControls, addPropertyControls } from "framer";
import { withHOC } from "./utils/withHOC";

const style: React.CSSProperties = {
  width: "100%",
  height: "100%"
};

const InnerTextStyles: React.SFC = props => {
  return <System.TextStyles {...props} style={style} />;
};

export const TextStyles = withHOC(InnerTextStyles);

TextStyles.defaultProps = {
  width: 150,
  height: 50
};

addPropertyControls(TextStyles, {
  as: {
    title: "As",
    options: [
      "object",
      "main",
      "time",
      "link",
      "menu",
      "dialog",
      "input",
      "label",
      "table",
      "header",
      "title",
      "button",
      "details",
      "a",
      "abbr",
      "address",
      "area",
      "article",
      "aside",
      "audio",
      "b",
      "base",
      "bdi",
      "bdo",
      "big",
      "blockquote",
      "body",
      "br",
      "canvas",
      "caption",
      "cite",
      "code",
      "col",
      "colgroup",
      "data",
      "datalist",
      "dd",
      "del",
      "dfn",
      "div",
      "dl",
      "dt",
      "em",
      "embed",
      "fieldset",
      "figcaption",
      "figure",
      "footer",
      "form",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "head",
      "hgroup",
      "hr",
      "html",
      "i",
      "iframe",
      "img",
      "ins",
      "kbd",
      "keygen",
      "legend",
      "li",
      "map",
      "mark",
      "menuitem",
      "meta",
      "meter",
      "nav",
      "noindex",
      "noscript",
      "ol",
      "optgroup",
      "option",
      "output",
      "p",
      "param",
      "picture",
      "pre",
      "progress",
      "q",
      "rp",
      "rt",
      "ruby",
      "s",
      "samp",
      "script",
      "section",
      "select",
      "small",
      "source",
      "span",
      "strong",
      "style",
      "sub",
      "summary",
      "sup",
      "tbody",
      "td",
      "textarea",
      "tfoot",
      "th",
      "thead",
      "tr",
      "track",
      "u",
      "ul",
      "var",
      "video",
      "wbr",
      "webview"
    ],
    optionTitles: [
      "Object",
      "Main",
      "Time",
      "Link",
      "Menu",
      "Dialog",
      "Input",
      "Label",
      "Table",
      "Header",
      "Title",
      "Button",
      "Details",
      "A",
      "Abbr",
      "Address",
      "Area",
      "Article",
      "Aside",
      "Audio",
      "B",
      "Base",
      "Bdi",
      "Bdo",
      "Big",
      "Blockquote",
      "Body",
      "Br",
      "Canvas",
      "Caption",
      "Cite",
      "Code",
      "Col",
      "Colgroup",
      "Data",
      "Datalist",
      "Dd",
      "Del",
      "Dfn",
      "Div",
      "Dl",
      "Dt",
      "Em",
      "Embed",
      "Fieldset",
      "Figcaption",
      "Figure",
      "Footer",
      "Form",
      "H1",
      "H2",
      "H3",
      "H4",
      "H5",
      "H6",
      "Head",
      "Hgroup",
      "Hr",
      "Html",
      "I",
      "Iframe",
      "Img",
      "Ins",
      "Kbd",
      "Keygen",
      "Legend",
      "Li",
      "Map",
      "Mark",
      "Menuitem",
      "Meta",
      "Meter",
      "Nav",
      "Noindex",
      "Noscript",
      "Ol",
      "Optgroup",
      "Option",
      "Output",
      "P",
      "Param",
      "Picture",
      "Pre",
      "Progress",
      "Q",
      "Rp",
      "Rt",
      "Ruby",
      "S",
      "Samp",
      "Script",
      "Section",
      "Select",
      "Small",
      "Source",
      "Span",
      "Strong",
      "Style",
      "Sub",
      "Summary",
      "Sup",
      "Tbody",
      "Td",
      "Textarea",
      "Tfoot",
      "Th",
      "Thead",
      "Tr",
      "Track",
      "U",
      "Ul",
      "Var",
      "Video",
      "Wbr",
      "Webview"
    ],
    defaultValue: "object",
    type: ControlType.Enum
  },
  variant: {
    title: "Variant",
    options: [
      "small",
      "tiny",
      "xSmall",
      "smallPlus",
      "medium",
      "mediumPlus",
      "large",
      "xLarge",
      "xLargePlus",
      "xxLarge",
      "xxLargePlus",
      "superLarge",
      "mega"
    ],
    optionTitles: [
      "Small",
      "Tiny",
      "XSmall",
      "SmallPlus",
      "Medium",
      "MediumPlus",
      "Large",
      "XLarge",
      "XLargePlus",
      "XxLarge",
      "XxLargePlus",
      "SuperLarge",
      "Mega"
    ],
    defaultValue: "small",
    type: ControlType.Enum
  },
  block: { title: "Block", defaultValue: false, type: ControlType.Boolean },
  nowrap: { title: "Nowrap", defaultValue: false, type: ControlType.Boolean },
  className: { title: "ClassName", defaultValue: "", type: ControlType.String },
  placeholder: {
    title: "Placeholder",
    defaultValue: "",
    type: ControlType.String
  }
});
